package:
    type:           composer-plugin
    name:           composer-asset-plugin
    title:          Composer plugin for bower/npm assets
    headline:       Composer Asset Plugin
    keywords:       composer, plugin, assets, bower, npm
    namespace:      hiqdev\composerassetplugin
    description:    |
        This [Composer](https://getcomposer.org/) plugin installs [bower](http://bower.io/)
        and [npm](https://npmjs.com/) dependencies using native npm and native bower or
        [PHP bower](http://bowerphp.org/).

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
