package:
    type:           composer-plugin
    name:           composer-asset-plugin
    namespace:      hiqdev\composerassetplugin
    composer:       Composer Asset Plugin
    title:          Composer plugin for bower/npm assets
    forum:          http://forum.hiqdev.com/
    keywords:       composer, plugin, assets, bower, npm
    description:    |
        This Compser plugin installs bower and npm dependencies using
        native npm and native or PHP bower.

require:
    hiqdev/hidev-vendor: "*"
    hiqdev/hidev-php:    "*"
